repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint # This is deprecated/frozen per https://github.com/golang/lint
    - id: go-imports
#    - id: go-cyclo
#      args: [-over=30]
    - id: validate-toml
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
    - id: go-mod-vendor
