package internal

// QueryVariables struct
type QueryVariables struct {
	ID       string      `json:"id,omitempty"`
	FilterBy interface{} `json:"filterBy,omitempty"`
	After    string      `json:"after,omitempty"`
	First    int         `json:"first,omitempty"`
}

// FilterBy struct
type FilterBy struct {
	Search []string `json:"search,omitempty"`
}

// EnumType struct
type EnumType struct {
	Type string `json:"type,omitempty"`
}

// ServiceAccountScopes defines the allowed service account rights
var ServiceAccountScopes = []string{
	"admin:all",
	"admin:audit",
	"admin:identity_providers",
	"admin:projects",
	"admin:reports",
	"admin:security_settings",
	"admin:users",
	"create:all",
	"create:automation_actions",
	"create:automation_rules",
	"create:cloud_configuration",
	"create:connectors",
	"create:controls",
	"create:outposts",
	"create:reports",
	"create:run_action",
	"create:run_control",
	"create:saved_cloud_event_filters",
	"create:saved_graph_queries",
	"create:scan_policies",
	"create:security_frameworks",
	"create:security_scans",
	"create:service_accounts",
	"create:service_tickets",
	"delete:all",
	"delete:automation_actions",
	"delete:automation_rules",
	"delete:cloud_configuration",
	"delete:connectors",
	"delete:controls",
	"delete:outposts",
	"delete:reports",
	"delete:saved_cloud_event_filters",
	"delete:saved_graph_queries",
	"delete:scan_policies",
	"delete:security_frameworks",
	"delete:security_scans",
	"delete:service_accounts",
	"read:all",
	"read:automation_actions",
	"read:automation_rules",
	"read:benchmarks",
	"read:cloud_accounts",
	"read:cloud_configuration",
	"read:cloud_event_rules",
	"read:cloud_events",
	"read:connectors",
	"read:controls",
	"read:inventory",
	"read:issue_settings",
	"read:issues",
	"read:kubernetes_clusters",
	"read:licenses",
	"read:outposts",
	"read:projects",
	"read:reports",
	"read:resources",
	"read:saved_cloud_event_filters",
	"read:saved_graph_queries",
	"read:scan_policies",
	"read:scanner_settings",
	"read:security_frameworks",
	"read:security_scans",
	"read:security_settings",
	"read:service_accounts",
	"read:system_activities",
	"read:users",
	"read:vulnerabilities",
	"update:all",
	"update:automation_actions",
	"update:automation_rules",
	"update:cloud_configuration",
	"update:cloud_event_rules",
	"update:connectors",
	"update:controls",
	"update:inventory",
	"update:issue_settings",
	"update:issues",
	"update:outposts",
	"update:resources",
	"update:saved_cloud_event_filters",
	"update:saved_graph_queries",
	"update:scan_policies",
	"update:scanner_settings",
	"update:security_frameworks",
	"update:security_scans",
	"update:service_accounts",
	"write:all",
	"write:automation_actions",
	"write:automation_rules",
	"write:cloud_configuration",
	"write:connectors",
	"write:controls",
	"write:issue_settings",
	"write:issues",
	"write:outposts",
	"write:reports",
	"write:saved_cloud_event_filters",
	"write:saved_graph_queries",
	"write:scan_policies",
	"write:scanner_settings",
	"write:security_frameworks",
	"write:security_scans",
	"write:service_accounts",
}
