name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
      id: go
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go build -v .
  lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - uses: danhunsaker/golang-github-actions@v1.3.1
      with:
        run: lint
  fmt:
    name: go-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - uses: danhunsaker/golang-github-actions@v1.3.1
      with:
        run: fmt
  imports:
    name: go-imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: check
      uses: danhunsaker/golang-github-actions@v1.3.1
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}
  generate:
    name: go-generate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
    - run: go generate ./...
    - name: git diff
      run: |
        git diff --exit-code || \
          (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
  test:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
      id: go
    - run: go test -v -cover ./internal/provider/... ./internal/client/... ./internal/config/... ./internal/utils/...
