name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - run: go mod download
    - run: go build -v .
  lint:
    name: go-lint
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - uses: danhunsaker/golang-github-actions@v1.3.1
      with:
        run: lint
  fmt:
    name: go-fmt
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - uses: danhunsaker/golang-github-actions@v1.3.1
      with:
        run: fmt
  imports:
    name: go-imports
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - name: check
      uses: danhunsaker/golang-github-actions@v1.3.1
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}
  generate:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false
    - uses: actions/setup-node@v3
    - run: go generate ./...
    - name: git diff
      run: |
        git diff --exit-code || \
          (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
  test:
    name: Matrix Test
    needs: build
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '0.13.*'
          - '0.14.*'
          - '0.15.*'
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - uses: actions/setup-node@v3
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix.terraform }}
        #terraform_wrapper: false
    - run: terraform fmt -check
    - run: go mod download
    - run: go test -v -cover ./internal/provider/
      timeout-minutes: 10
      env:
        TF_ACC: "1"
        #TF_VAR_WIZ_URL: ${{ secrets.WIZ_URL }}
        #TF_VAR_WIZ_AUTH_CLIENT_ID: ${{ secrets.WIZ_AUTH_CLIENT_ID }}
        #TF_VAR_WIZ_AUTH_CLIENT_SECRET: ${{ secrets.WIZ_AUTH_CLIENT_SECRET }}
        #TF_VAR_PROXY: ${{ secrets.PROXY }}
        #TF_VAR_PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
        #TF_VAR_CA_CHAIN: ${{ secrets.CA_CHAIN }}
        #WIZ_URL: ${{ secrets.WIZ_URL }}
        #WIZ_AUTH_CLIENT_ID: ${{ secrets.WIZ_AUTH_CLIENT_ID }}
        #WIZ_AUTH_CLIENT_SECRET: ${{ secrets.WIZ_AUTH_CLIENT_SECRET }}
        #PROXY: ${{ secrets.PROXY }}
        #PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
        #CA_CHAIN: ${{ secrets.CA_CHAIN }}
        CGO_ENABLED: 0
